# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230817-132339-nimble-curve

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# Define your policies at the top level
policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100

# Rule-Based + ML (DIETClassifier) Pipeline
pipeline_rule_ml:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100

# ML (DIETClassifier) + Transformer Pipeline
pipeline_ml_transformer:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: LanguageModelTokenizer
  model_name: "bert"
  model_weights: "bert-base-uncased"

# Rule-Based + Transformer Pipeline
pipeline_rule_transformer:
- name: WhitespaceTokenizer
- name: RulePolicy
- name: LanguageModelTokenizer
  model_name: "bert"
  model_weights: "bert-base-uncased"
pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
